version: "2"

run:
  issues-exit-code: 1

formatters:
  enable:
    - gofmt
    - gci

linters:
  enable:
    - wrapcheck
  settings:
    wrapcheck:
      ignore-package-globs:
        # We already make sure your own packages wrap errors properly
        - github.com/symfony-cli/*
    errcheck:
        exclude-functions:
          - github.com/symfony-cli/terminal.Print
          - github.com/symfony-cli/terminal.Printf
          - github.com/symfony-cli/terminal.Println
          - github.com/symfony-cli/terminal.Printfln
          - github.com/symfony-cli/terminal.Eprint
          - github.com/symfony-cli/terminal.Eprintf
          - github.com/symfony-cli/terminal.Eprintln
          - github.com/symfony-cli/terminal.Eprintfln
          - github.com/symfony-cli/terminal.Eprint
          - github.com/symfony-cli/terminal.SetLogLevel
          - fmt.Fprintln
          - fmt.Fprintf
          - fmt.Fprint
  exclusions:
    presets:
      - std-error-handling
      - common-false-positives
    rules:
      - path: _test\.go
        linters:
          - errcheck
        text: "(?i)Error return value of .(os\\.(Chdir|Rename)|io\\.Copy). is not checked"
      - path: _test\.go
        linters:
          - errcheck
        text: "(?i)Error return value of .flags\\.Set. is not checked"
