before:
  hooks:
    - go mod download

changelog:
  sort: desc
  use: github
  filters:
    exclude:
    - Merge branch
    - Merge pull request

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: 386
    main: ./
    binary: symfony
    ldflags: -s -w -X 'main.channel={{ if index .Env "AUTOUPDATE_CHANNEL" }}{{ .Env.AUTOUPDATE_CHANNEL }}{{ else }}dev{{ end }}' -X 'main.buildDate={{ .Date }}' -X 'main.version={{ .Version }}'
    flags:
      - -trimpath

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
    - goos: windows
      format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

# create a source tarball
# https://goreleaser.com/customization/source/
source:
  enabled: true

snapshot:
  name_template: "next"

universal_binaries:
  - replace: true
    name_template: symfony

# sign all artifacts
# https://goreleaser.com/customization/sign
signs:
- cmd: cosign
  env:
  - COSIGN_EXPERIMENTAL=1
  certificate: '${artifact}.pem'
  args:
    - sign-blob
    - '--output-certificate=${certificate}'
    - '--output-signature=${signature}'
    - '${artifact}'
  artifacts: all
  output: true

release:
  footer: |
    **Full Changelog**: https://github.com/symfony-cli/symfony-cli/compare/{{ .PreviousTag }}...{{ .Tag }}

brews:
  - tap:
      owner: symfony-cli
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    commit_author:
      name: Fabien Potencier
      email: fabien@symfony.com
    folder: Formula
    goarm: "7"
    homepage: https://symfony.com
    description: Symfony CLI helps Symfony developers manage projects, from local code to remote infrastructure
    license: AGPL-3.0
    test: |
      system "#{bin}/symfony version"
    dependencies:
    - name: git
      type: optional
    install: |-
      bin.install "symfony"
    service: |-
      run ["#{bin}/symfony", "local:proxy:start", "--foreground"]
      keep_alive true

nfpms:
  - file_name_template: '{{ .ConventionalFileName }}'
    id: packages
    homepage: https://symfony.com
    description: Symfony CLI helps Symfony developers manage projects, from local code to remote infrastructure
    maintainer: Fabien Potencier <fabien@symfony.com>
    license: AGPL-3.0
    vendor: Symfony
    formats:
    - apk
    - deb
    - rpm
    recommends:
    - git

dockers:
  - image_templates: [ "ghcr.io/symfony-cli/{{ .ProjectName }}:{{ .Version }}-amd64" ]
    goarch: amd64
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.source=https://github.com/symfony-cli/symfony-cli"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - image_templates: [ "ghcr.io/symfony-cli/{{ .ProjectName }}:{{ .Version }}-arm64" ]
    goarch: arm64
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.source=https://github.com/symfony-cli/symfony-cli"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

docker_manifests:
  - name_template: ghcr.io/symfony-cli/{{ .ProjectName }}:{{ .Version }}
    image_templates: &docker_images
      - ghcr.io/symfony-cli/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/symfony-cli/{{ .ProjectName }}:{{ .Version }}-arm64
  - name_template: ghcr.io/symfony-cli/{{ .ProjectName }}:v{{ .Major }}
    image_templates: *docker_images
  - name_template: ghcr.io/symfony-cli/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}
    image_templates: *docker_images
  - name_template: ghcr.io/symfony-cli/{{ .ProjectName }}:latest
    image_templates: *docker_images

chocolateys:
  -
    owners: Symfony
    title: Symfony CLI
    authors: Symfony
    project_url: https://symfony.com/

    # Template for the url which is determined by the given Token (github,
    # gitlab or gitea)
    # Default depends on the client.
    url_template: "https://github.com/foo/bar/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    # App's icon.
    # Default is empty.
    icon_url: 'https://rawcdn.githack.com/foo/bar/efbdc760-395b-43f1-bf69-ba25c374d473/icon.png'
    copyright: 2021-present Fabien Potencier
    license_url: https://github.com/symfony-cli/symfony-cli/blob/main/LICENSE
    project_source_url: https://github.com/symfony-cli/symfony-cli
    bug_tracker_url: https://github.com/symfony-cli/symfony-cli/issues
    summary: Symfony CLI helps Symfony developers manage projects, from local code to remote infrastructure
    description: Symfony CLI helps Symfony developers manage projects, from local code to remote infrastructure
    release_notes: "https://github.com/symfony-cli/symfony-cli/releases/tag/v{{ .Version }}"
    api_key: '{{ .Env.CHOCOLATEY_API_KEY }}'

    # The source repository that will push the package to.
    #
    # Defaults are shown below.
    source_repo: "https://push.chocolatey.org/"

    # Setting this will prevent goreleaser to actually try to push the package
    # to chocolatey repository, leaving the responsability of publishing it to
    # the user.
    skip_publish: false
