name: Integration tests

on:
    pull_request:
    push:

jobs:
    tests:
        name: Integration test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 0

            -   name: Set up Go
                uses: actions/setup-go@v3
                with:
                    go-version: '^1.21.1'

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.3

            -   uses: actions/cache@v3
                with:
                    path: |
                        ~/.cache/go-build
                        ~/go/pkg/mod
                    key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
                    restore-keys: |
                        ${{ runner.os }}-go-

            -   name: Build SUT
                run: |
                    go build .

            -   name: Run tests
                run: go test -v --tags=integration ./integration/...
